/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { startTransition, useEffect, useRef, useState } from "react";
import { useAnimations, useGLTF } from "@react-three/drei";
import { useAvatarState } from "../hooks/useAvatarState";
import { useFrame } from "@react-three/fiber";
import * as THREE from "three";
import {
  avatarState,
  expressionType,
  facialExpressions,
  lipsyncManager,
} from "../utils/helperConfig";

export function Avatar(props) {
  const { animation, message, setAnimation, setMessage, setAction } =
    useAvatarState();

  const group = useRef();
  const audio = useRef(new Audio());

  const [facialExpression, setFacialExpression] = useState("default");
  const [blink, setBlink] = useState(false);

  const { nodes, materials, scene } = useGLTF(
    "/models/69433ff2a8aaca09962ed9c3.glb"
  );
  const { animations } = useGLTF("/models/animations.glb");
  const { actions } = useAnimations(animations, group);

  const handleEnded = () => {
    startTransition(() => {
      setAnimation("Idle");
      setFacialExpression("default");
      setMessage(null);
      setAction(avatarState.idle);
    });
  };

  useEffect(() => {
    let requestId;
    const analyzeAudio = () => {
      requestId = requestAnimationFrame(analyzeAudio);
      lipsyncManager.processAudio();
    };

    analyzeAudio();

    return () => cancelAnimationFrame(requestId);
  }, []);

  useEffect(() => {
    const action = actions[animation];
    if (!action) return;

    action.reset().fadeIn(0.5).play();

    return () => {
      action?.fadeOut(0.5);
    };
  }, [animation, actions]);

  useEffect(() => {
    if (!message) return;

    startTransition(() => {
      setAnimation(message.animation);
      setFacialExpression(message.facialExpression);
      setAction(avatarState.speaking);
    });

    if (audio.current) {
      audio.current.pause();
      audio.current.removeEventListener("ended", handleEnded);
      audio.current = null;
    }

    const audioFile = new Audio("data:audio/mp3;base64," + message.audio);
    audio.current = audioFile;
    lipsyncManager.connectAudio(audioFile);

    audioFile.play();
    audioFile.addEventListener("ended", handleEnded);

    return () => {
      audioFile.pause();
      audioFile.removeEventListener("ended", handleEnded);
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [message, setAction, setAnimation]);

  useEffect(() => {
    let blinkTimeout;

    const blinkLoop = () => {
      blinkTimeout = setTimeout(() => {
        setBlink(true);
        setTimeout(() => {
          setBlink(false);
          blinkLoop();
        }, 200);
      }, THREE.MathUtils.randInt(1500, 5000));
    };

    blinkLoop();

    return () => clearTimeout(blinkTimeout);
  }, []);

  const lerpMorphTarget = (target, value, speed = 0.1) => {
    scene.traverse((mesh) => {
      if (!mesh.isSkinnedMesh || !mesh.morphTargetDictionary) return;

      const index = mesh.morphTargetDictionary[target];
      if (
        index === undefined ||
        mesh.morphTargetInfluences[index] === undefined
      )
        return;

      mesh.morphTargetInfluences[index] = THREE.MathUtils.lerp(
        mesh.morphTargetInfluences[index],
        value,
        speed
      );
    });
  };

  useFrame(() => {
    const expression =
      facialExpressions[facialExpression] ?? expressionType.default;
    const morphTargets = nodes.EyeLeft.morphTargetDictionary;

    Object.keys(morphTargets).forEach((key) => {
      if (key === "eyeBlinkLeft" || key === "eyeBlinkRight") return;

      if (expression && expression[key]) {
        lerpMorphTarget(key, expression[key], 0.1);
      } else {
        lerpMorphTarget(key, 0, 0.1);
      }
    });

    lerpMorphTarget("eyeBlinkLeft", blink ? 1 : 0, 0.5);
    lerpMorphTarget("eyeBlinkRight", blink ? 1 : 0, 0.5);

    const viseme = lipsyncManager.viseme;
    const state = lipsyncManager.state;

    lerpMorphTarget(viseme, 1, state === "vowel" ? 0.2 : 0.4);
  });

  return (
    <group {...props} dispose={null} ref={group}>
      <primitive object={nodes.Hips} />
      <skinnedMesh
        name="EyeLeft"
        geometry={nodes.EyeLeft.geometry}
        material={materials.Wolf3D_Eye}
        skeleton={nodes.EyeLeft.skeleton}
        morphTargetDictionary={nodes.EyeLeft.morphTargetDictionary}
        morphTargetInfluences={nodes.EyeLeft.morphTargetInfluences}
      />
      <skinnedMesh
        name="EyeRight"
        geometry={nodes.EyeRight.geometry}
        material={materials.Wolf3D_Eye}
        skeleton={nodes.EyeRight.skeleton}
        morphTargetDictionary={nodes.EyeRight.morphTargetDictionary}
        morphTargetInfluences={nodes.EyeRight.morphTargetInfluences}
      />
      <skinnedMesh
        name="Wolf3D_Head"
        geometry={nodes.Wolf3D_Head.geometry}
        material={materials.Wolf3D_Skin}
        skeleton={nodes.Wolf3D_Head.skeleton}
        morphTargetDictionary={nodes.Wolf3D_Head.morphTargetDictionary}
        morphTargetInfluences={nodes.Wolf3D_Head.morphTargetInfluences}
      />
      <skinnedMesh
        name="Wolf3D_Teeth"
        geometry={nodes.Wolf3D_Teeth.geometry}
        material={materials.Wolf3D_Teeth}
        skeleton={nodes.Wolf3D_Teeth.skeleton}
        morphTargetDictionary={nodes.Wolf3D_Teeth.morphTargetDictionary}
        morphTargetInfluences={nodes.Wolf3D_Teeth.morphTargetInfluences}
      />
      <skinnedMesh
        geometry={nodes.Wolf3D_Body.geometry}
        material={materials.Wolf3D_Body}
        skeleton={nodes.Wolf3D_Body.skeleton}
      />
      <skinnedMesh
        geometry={nodes.Wolf3D_Outfit_Bottom.geometry}
        material={materials.Wolf3D_Outfit_Bottom}
        skeleton={nodes.Wolf3D_Outfit_Bottom.skeleton}
      />
      <skinnedMesh
        geometry={nodes.Wolf3D_Outfit_Footwear.geometry}
        material={materials.Wolf3D_Outfit_Footwear}
        skeleton={nodes.Wolf3D_Outfit_Footwear.skeleton}
      />
      <skinnedMesh
        geometry={nodes.Wolf3D_Outfit_Top.geometry}
        material={materials.Wolf3D_Outfit_Top}
        skeleton={nodes.Wolf3D_Outfit_Top.skeleton}
      />
    </group>
  );
}

useGLTF.preload("/models/69433ff2a8aaca09962ed9c3.glb");
